-- Create simulator_logs table for tracking usage
CREATE TABLE IF NOT EXISTS public.simulator_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address text NOT NULL,
    message_count int DEFAULT 1,
    last_activity timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add index on ip_address for faster lookups
CREATE INDEX IF NOT EXISTS idx_simulator_logs_ip ON public.simulator_logs(ip_address);

-- Enable RLS
ALTER TABLE public.simulator_logs ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read/insert/update (logic handled in client for now, ideally server-side)
-- Validating IP matches is hard without server, so we trust client for this demo but in prod use Edge Functions
CREATE POLICY "Allow public access to logs" ON public.simulator_logs
    FOR ALL USING (true) WITH CHECK (true);
