-- Create leads table
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  whatsapp text not null,
  chat_volume text not null,
  status text default 'new'::text
);

-- Enable RLS
alter table public.leads enable row level security;

-- Create policies
create policy "Enable insert for everyone" on public.leads
  for insert with check (true);

create policy "Enable read access for authenticated users only" on public.leads
  for select using (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on public.leads
  for update using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only" on public.leads
  for delete using (auth.role() = 'authenticated');
