-- Create seo_pages table
create table if not exists public.seo_pages (
  id bigint generated by default as identity primary key,
  page_path text not null unique,
  title text,
  description text,
  keywords text,
  og_image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.seo_pages enable row level security;

-- Policies
create policy "Public pages are viewable by everyone"
  on public.seo_pages for select
  using ( true );

create policy "Admins can insert seo_pages"
  on public.seo_pages for insert
  with check ( auth.role() = 'authenticated' );

create policy "Admins can update seo_pages"
  on public.seo_pages for update
  using ( auth.role() = 'authenticated' );

create policy "Admins can delete seo_pages"
  on public.seo_pages for delete
  using ( auth.role() = 'authenticated' );

-- Insert default home page data (Optional)
insert into public.seo_pages (page_path, title, description)
values ('/', 'Vlow.AI - Scale Bisnis Kamu dengan AI Agent', 'Otomatisasi support customer dengan Vlow.AI. AI agent cerdas yang handle WhatsApp, Instagram, dan lainnya 24/7.')
on conflict (page_path) do nothing;
